### ISSUE TITLE
How to Browse

### ISSUE THREAD

**Issue by dgmltn** [svrooij/sonos2mqtt#105]
Thanks for the updated documentation, it helped a bunch. I'm just still having trouble with the browsing commands. This one works:

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "GetFavorites",
    "reply": "GetFavoritesReply"
  }
}
```

And it looks like it's a shortcut to this one. But this one doesn't work (I've tried many variations on both BrowseParsed and BrowseParsedWithDefaults). I'm assuming once I figure this one out, searching by artist (like [here](https://github.com/svrooij/node-sonos-ts/blob/master/examples/content.js)) or searching for all playlists ("SQ:") will be obvious.

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "ContentDirectoryService.BrowseParsedWithDefaults",
    "input": {
      "ObjectID": "FV:2"
    },
    "reply": "GetFavoritesReply"
  }
}
```

=>
```json
{"command":"adv-command","error":{"Action":"Browse","FaultCode":"s:Client","Fault":"UPnPError","UpnpErrorCode":701,"name":"SonosError"}}
```

**Comment by dgmltn** [comment]
Ok, here's the formula:

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "ContentDirectoryService.BrowseParsedWithDefaults",
    "val": "FV:2",
    "reply": "GetFavoritesReply"
  }
}
```

**Comment by svrooij** [comment]
According to the [code](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L195-L197).
Both your calls should work.

```JSON
{
  "command": "adv-command",
  "input": {
    "cmd": "GetFavorites",
    "reply": "GetFavoritesReply"
  }
}
```

should result in the same code being called as

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "ContentDirectoryService.BrowseParsedWithDefaults",
    "val": "FV:2",
    "reply": "GetFavoritesReply"
  }
}
```

Here you can find more on browsing https://github.com/svrooij/node-sonos-ts/blob/master/examples/content.js
