### ISSUE TITLE
the new command reply feature don't work any more 

### ISSUE THREAD

**Issue by heinz-otto** [svrooij/sonos2mqtt#106]
I think the merged Version 3.0.7  - the new command reply feature don't work any more like in the beta Version  sonos2mqtt@3.0.7-beta.2 from yesterday.

I am wrong?

**Comment by svrooij** [comment]
If you check the actions, you’ll see that I did something wrong.
https://github.com/svrooij/sonos2mqtt/actions

So actually 3.0.7 is the version before the reply feature. And 3.0.7.beta.2 is a newer version and should actually be called 3.0.8.beta.1

I wanted the release the documentation and not the new reply feature so I cancelled a build, but I was to late.

**Comment by heinz-otto** [comment]
No Problem at all. beta.2 is working. Thomas and me was a little bit confused during this afternoon :)

**Comment by svrooij** [comment]
Will get solved with the next release. So if you think of any thing before that....
