### ISSUE TITLE
npm install -g failed

### ISSUE THREAD

**Issue by Wuppi68** [svrooij/sonos2mqtt#113]
After installing s2m with
**npm install -g sonos2mqtt**

the 1st line of the "executable" is missing

diff :-)
`diff sonos2mqtt /usr/bin/sonos2mqtt 
0a1,2
> #!/usr/bin/env node
> `

sorry didn't find this file in the git :-(

Thx Wuppi68 from fhem forum

**Comment by Wuppi68** [comment]
found a hint @ https://github.com/gajus/gitdown/issues/38

**Comment by svrooij** [comment]
Never had this issue, what version of node are you using?

**Comment by svrooij** [comment]
@Wuppi68 can you check if it works when you install it like `npm install -g sonos2mqtt@3.0.9-beta.2` (with the version number where I fixed it)
