### ISSUE TITLE
[feature request] having bass and treble state retain somewhere

### ISSUE THREAD

**Issue by 10w73** [svrooij/sonos2mqtt#114]
For an EQ integration into homekit I need to read bass and treble. Is it possible to have them both retain somewhere at the same time? …/status/eq would be great. Unfortunately  I'm not much of as .js guy.

**Comment by 10w73** [comment]
Thx for doing this so quickly. However it only shows the last changed of the two in the main status object. I need to see them both at every the time. I think this is also intended behaviour.

**Comment by svrooij** [comment]
Can you please skip the **need** and **should**? They sound demanding. For instance *I need time or money to spend on this project, so if you want this fixed you should [sponsor](https://github.com/sponsors/svrooij) me*.

**Comment by 10w73** [comment]
I said ... to what **should** happen after you place a flag ... So what the interpreter **should** do after he reads the flag. I told you that so that you know were I put the code in your files.

I don‘t get what‘s wrong here. Also not at all I wanted to sound demanding. Have you never had to sit in a review? I never wanted to tell you what you have to do! I was very grateful that you did what you did and I thanked you for doing that so quickly. I was talking „intended behavior“ of your code. This means what it „should“ do if there were no bugs. You added bass and treble to the main object but it only works once. So this seemed like a bug and I told you. And yes this is output of your software ... The broker is mosquitto and it looks exactly like that. And I would of course sponsor you. But why would I do that before the software works? That sounds kinda demanding too, huh? I talked completely from a tester and developer point of view. If that sounded rude to you: Sorry. I would **need** this and that if I wanted to make use of your code. I don‘t **need** you to do something. That are different things! Also that‘s not my first language.

**Comment by 10w73** [comment]
How frequently do you think I could call `getBass` and `getTreble` via an avr_command to route the output to I. E. .../eq/Bass and .../eq/Treble in order to read that instead?

**Comment by svrooij** [comment]
Let's keep it at a difference in language interpretation.

> How frequently do you think I could call getBass and getTreble via an adv_command to route the output to I. E. .../eq/bass and .../eq/treble in order to read that instead?

once a second, I guess (it depends on your sonos speakers to respond quick enough.)

In all the apps I use to connect to mqtt, the output of the [player status](https://svrooij.io/sonos2mqtt/topics.html#player-status) looks like the sample below.

Anyhow, the status object will keep the last value for `bass` and `treble` in [this release](https://github.com/svrooij/sonos2mqtt/releases/tag/v3.0.10-beta.2). So they are available there, and won't get removed with an update that doesn't have the values set.

```json
{
  "uuid" : "RINCON_000E5000000001400",
  "name" : "Kantoor",
  "groupName" : "Kantoor",
  "coordinatorUuid" : "RINCON_000E5000000001400",
  "currentTrack" : {
    "Album" : "Hard Bass 2012 Mixed by The Pitcher, Luna, Frontliner and Chris One",
    "Artist" : "Pavo",
    "AlbumArtUri" : "http://192.168.1.105:1400/getaa?s=1&u=x-sonos-spotify:spotify:track:3Je8RHcdTJ8NGG3krmCHUd%3fsid%3d9%26flags%3d8224%26sn%3d7",
    "Title" : "Let’s Go! - Radio Edit",
    "UpnpClass" : "object.item.audioItem.musicTrack",
    "Duration" : "0:04:06",
    "ItemId" : "-1",
    "ParentId" : "-1",
    "TrackUri" : "x-sonos-spotify:spotify:track:3Je8RHcdTJ8NGG3krmCHUd?sid=9&flags=8224&sn=7",
    "ProtocolInfo" : "sonos.com-spotify:*:audio/x-spotify:*"
  },
  "transportState" : "PLAYING",
  "playmode" : "SHUFFLE",
  "ts" : 1586344373119,
  "volume" : {
    "Master" : 7,
    "LF" : 100,
    "RF" : 100
  },
  "mute" : {
    "Master" : false,
    "LF" : false,
    "RF" : false
  },
  "treble": 0,
  "bass": 0
}
```

**Comment by 10w73** [comment]
Ah! Great to hear that. Thank you! 

I still have the problem that after starting sonos2mqtt it seems to work and I get something like that:

`{"uuid":"RINCON_48A6B8E4276E01400","name":"Move","groupName":"Move","coordinatorUuid":"RINCON_48A6B8E4276E01400","currentTrack":{"Album":"Soft Planet - EP","Artist":"Sweeps","AlbumArtUri":"http://192.168.178.49:1400/getaa?v=0&vli=1&u=290294128","Title":"Red Helix","UpnpClass":"object.item.audioItem.musicTrack","Duration":"0:01:58","ItemId":"-1","ParentId":"-1","TrackUri":"undefined"},"enqueuedMetadata":{"Title":"","UpnpClass":"object.item.audioItem.linein.airplay","ItemId":"-1","ParentId":"-1"},"nextTrack":{"UpnpClass":"object.item.audioItem.musicTrack","ItemId":"-1","ParentId":"-1"},"transportState":"PLAYING","playmode":"NORMAL","ts":1596300302633,"volume":{"Master":21,"LF":100,"RF":100},"mute":{"Master":false,"LF":false,"RF":false},"bass":-10,"treble":0}
`

but after changing bass or treble it behaves like before and just keeps the changed value:

`{"uuid":"RINCON_48A6B8E4276E01400","name":"Move","groupName":"Move","coordinatorUuid":"RINCON_48A6B8E4276E01400","currentTrack":{"Album":"Lifted Quest - EP","Artist":"J. Raise, Jr","AlbumArtUri":"http://192.168.178.49:1400/getaa?v=0&vli=1&u=832534634","Title":"Junkyard","UpnpClass":"object.item.audioItem.musicTrack","Duration":"0:02:41","ItemId":"-1","ParentId":"-1","TrackUri":"undefined"},"enqueuedMetadata":{"Title":"","UpnpClass":"object.item.audioItem.linein.airplay","ItemId":"-1","ParentId":"-1"},"nextTrack":{"UpnpClass":"object.item.audioItem.musicTrack","ItemId":"-1","ParentId":"-1"},"transportState":"PLAYING","playmode":"NORMAL","ts":1596300407733,"treble":-10}`

In this case it was treble set to -10 and the info about the bass value is gone. 

It think you are on the right track. I'll also started sponsoring your efforts right away.

**Comment by svrooij** [comment]
Can you do a `sonos2mqtt --version` (if running locally) or at least check you have the latest version, at my machine i'm getting both values. Running **3.0.10-beta.2** [this release](https://github.com/svrooij/sonos2mqtt/releases/tag/v3.0.10-beta.2)

I've updated to and from 0 and every time the last message actually has both values.

**Comment by 10w73** [comment]
Arghhh … of course it was 3.0.10-beta.1. Yesterday i didn't use the npm install -g option and it somehow got stuck local and messed up the PATH. It is working. Great job!
