### ISSUE TITLE
Getting stuck without fully crashing after a couple of hours running in pm2

### ISSUE THREAD

**Issue by 10w73** [svrooij/sonos2mqtt#116]
After a couple of hours it get's stuck while running in pm2. But it seems not to crash fully/ exit because pm2 isn't restarting it. So it stops working completely.

The logs then show this:

```
FetchError: request to http://192.168.178.49:1400/ZoneGroupTopology/Event failed, reason: connect ETIMEDOUT 192.168.178.49:1400
6|sonos2mq |     at ClientRequest.<anonymous> (/home/pi/.nvm/versions/node/v12.18.3/lib/node_modules/sonos2mqtt/node_modules/node-fetch/lib/index.js:1455:11)
6|sonos2mq |     at ClientRequest.emit (events.js:315:20)
6|sonos2mq |     at Socket.socketErrorListener (_http_client.js:426:9)
6|sonos2mq |     at Socket.emit (events.js:315:20)
6|sonos2mq |     at emitErrorNT (internal/streams/destroy.js:92:8)
6|sonos2mq |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
6|sonos2mq |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
6|sonos2mq |   type: 'system',
6|sonos2mq |   errno: 'ETIMEDOUT',
6|sonos2mq |   code: 'ETIMEDOUT'
6|sonos2mq | }
```

But as said it didn't seem to crash because pm2 shows it's running and isn't restarting it.

I am running v3.0.10-beta.2 from #114

**Comment by svrooij** [comment]
This is related to [this comment](https://github.com/svrooij/sonos2mqtt/issues/112#issuecomment-667574226).

It used a subscription to monitor group changes, sometimes they don't succeed. In the **not released** version of node-sonos-ts there is the beginning of a fix.

**Comment by svrooij** [comment]
Are you running on a device that went to sleep?

Or do you have a clue why the Sonos speaker wasn't reachable from the device you're running this library?

**Comment by 10w73** [comment]
On of my devices is a Sonos Move that goes to sleep every now and then. Is there something I can configure differently to prevent this or is this also connected to the problem with node-sonos-ts?

**Comment by svrooij** [comment]
Is that the only Sonos speaker you have? And is the IP above the IP of the move?
If you have other Sonos players that don’t go to sleep, you should set one of those as the initial device. It will then subscribe for events from the always connected player. And with the above described changes (unreleased, as in work-in-progress) your connection should be a lot more stable.

If you only have one Sonos move, this app will never become reliable because it doesn’t know when the speaker disconnected and is no longer sending events.

**Comment by 10w73** [comment]
Thankfully I got another one. I now use --device to force to set the stationary one as the initial device. I'm looking forward to the update of node-sonos-ts.

**Comment by 10w73** [comment]
Great. That was fast. Just updated it (and checked --version this time). I had it running with a cron parameter that forced a restart every hour. I disabled that to check if it works out now.

**Comment by svrooij** [comment]
Let us know if this solves your issue, then we can release this to latest and have everybody profit from it.

**Comment by 10w73** [comment]
Until now everything looks fine. I would suggest to wait another day just to be sure because it was so sporadically. But I think it is working. Great job!

**Comment by 10w73** [comment]
Today it got stuck again even though the move was in the cradle and should have been on all the time. I got

```
7|sonos2mq | FetchError: request to http://192.168.178.49:1400/MediaRenderer/AVTransport/Event failed, reason: connect ETIMEDOUT 192.168.178.49:1400
7|sonos2mq |     at ClientRequest.<anonymous> (/home/pi/.nvm/versions/node/v12.18.3/lib/node_modules/sonos2mqtt/node_modules/node-fetch/lib/index.js:1455:11)
7|sonos2mq |     at ClientRequest.emit (events.js:315:20)
7|sonos2mq |     at Socket.socketErrorListener (_http_client.js:426:9)
7|sonos2mq |     at Socket.emit (events.js:315:20)
7|sonos2mq |     at emitErrorNT (internal/streams/destroy.js:92:8)
7|sonos2mq |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
7|sonos2mq |     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
7|sonos2mq |   type: 'system',
7|sonos2mq |   errno: 'ETIMEDOUT',
7|sonos2mq |   code: 'ETIMEDOUT'
7|sonos2mq | }
```

It again refers to 192.168.178.49 which is the Sonos Move. I am very sure I started sonos2mqtt via pm2 with

`pm2 start sonos2mqtt -- --device 192.168.178.54 --prefix "/home/sonos"` (where 192.168.178.54 is the always on stationary one)

I now used pm2 delete to delete the service and started it again with a little pm2 save on top. I will look at the logs again tomorrow.

**Comment by svrooij** [comment]
It displays an different error. This application will subscribe to events from all speakers. With the latest change it refreshes the subscription more often and if it fails it retries after 10 minutes.

It is still an error though, that is why it is showing up in the logs.

this `MediaRenderer/AVTransport/Event` is the endpoint it tries to subscribe. That means the re subscribe to the AVTransport events failed. Previously it was the `/ZoneGroupTopology/Event` which is important to keep the zones correctly.

You can also send a mqtt message to `sonos/cmd/check-subscriptions` for it to force refresh all subscriptions.

**Comment by svrooij** [comment]
If you configure PM2 to set some https://pm2.keymetrics.io/docs/usage/environment/
Environment variables, you could see that it would still refresh the subscriptions.

Set `DEBUG` to `sonos:*` you get a lot more debug messages.

**Comment by 10w73** [comment]
> It displays an different error.

You are absolutely right. I missed that. It was reproducible today with one slight difference. Yesterday I just caught it because the Move speaker wasn't responding to commands I sent and then I checked the logs and had to restart the process to make it work again. Today after I woke up the speaker from sleep everything still is working fine. I think there may be something left that is able to confuse it but it is safe to say that is mostly working as supposed and would be a good update to the existing release.

**Comment by svrooij** [comment]
I just discovered that the sonos speakers don't try to keep the original issued IP.
So for an even more reliable connection you should set the IP's to fixed on your router if possible.

This library doesn't handle changes in IP well....
