### ISSUE TITLE
More details possible ?

### ISSUE THREAD

**Issue by TaGGoU91** [svrooij/sonos2mqtt#124]
Hello,

Thanks for this github project.
I am coming to you to ask if it is possible to have more data sent to broker ?
I want to have a good integration in my home automation system. i am using jeedom and i need as far as i see one more information, which is the model of the speaker (play 1 / play 3 / etc).

Thanks for your help
TaG

**Comment by svrooij** [comment]
You can probably enable this by changing the code. Not sure where you can get the model without loading the device description xml.

Accepting a PR for this

**Comment by TaGGoU91** [comment]
Hello, i am using your docker image like this : svrooij/sonos2mqtt, I do not know how to have this correction available ? I have stopped the docker and restart, but there is not this informations.
I assume that this because of the fact that you said it is available in npm package and GitHub release only ?

Thanks for adding it, and thanks for your help on this.
TaG

**Comment by svrooij** [comment]
have you tried pulling a new version of the image?

`docker pull svrooij/sonos2mqtt`
