### ISSUE TITLE
No Player Status

### ISSUE THREAD

**Issue by willchr** [svrooij/sonos2mqtt#130]
Hi,

Happy New Year to all of you!

I have installed the dockerimage and actually everything runs fine. After starting the container the bridge detects all my 9 speaker. I can send commands to every of them it these commands will be confirmed via mqtt ( sonos/uuid/control).

What I do not receive are any changes made by the sonos app (ios) or the current status at all.

Any ideas?

Best Regards
Christian

**Comment by svrooij** [comment]
Yes I’ve got an idea. You did not setup the `SONOS_LISTENER_HOST` as described in the [getting started](https://svrooij.io/sonos2mqtt/getting-started.html#run-sonos2mqtt-in-docker)

That is my first guess, it fits you issue completely. You can re-open if that wasn’t the case.
