### ISSUE TITLE
Topic to help identify Track/Album/Playlist

### ISSUE THREAD

**Issue by dirstel** [svrooij/sonos2mqtt#132]
I tried a lot playing tracks/albums/playlists from different services. Thanks to your help, the integration with deezer works well. When trying to identify what to play, I had the idea of a reverse meta-data-helper:

Implement a (set of) topic(s) that give the ID of Track/Album/Playlist of the current playing music.

f.e. that may be a subtopic of the speaker(group) /sonos/speaker/. That would help some sort of automation to "store" a playing album. An entry in the info message would be ok too.

Usecase:
* select an album/track/playlist from your favorite service
* listen to topic and grab information needed to readd the desired item

As far as I can see, it is not that easy, to identify, what sort of item (album/track/playllist) is selected for playback. that may be adressed by giving serveral topics and one can use the one which holds the desired information.

**Comment by svrooij** [comment]
The upstream sonos library (also mine) has basic **beta** support for [external music services](https://svrooij.io/node-sonos-ts/sonos-device/external-music-services.html), I'm not sure how to implement this into sonos2mqtt though.

That isn't really event based but more request/response based.

**Comment by dirstel** [comment]
> That isn't really event based but more request/response based.
the event would be selecting and playing audio by sonos app. that already sends a message with lots of info. I'd like to have some sort of "revers"encoding of this infos to sth. understandable by the enqueuri command. 

f.e. I'd like to play an album by app and that sends a mqtt-message containing sth. like "spotify:album:00000000". That value would be a breeze to store away and recall in order to select that album again.

**Comment by svrooij** [comment]
This library made it easy to play Spotify for instance by accepting the Spotify uri (that you can copy in the Spotify app). But generating the Spotify uri from the track uri is not implemented (yet).

what is the reason you cannot store the current track uri?

I’m open for a PR that supports this, so if you want to give it a go....
