### ISSUE TITLE
Don't know how to write message

### ISSUE THREAD

**Issue by viimD** [svrooij/sonos2mqtt#133]
I just installed Sonos2mqtt and 2 speakers are visible in MQTT explorer. 

Now i try to increase the volume with a flow in Node-RED. Therefore I inject a msg.payload.Volume.Master with number 30 into an mqtt out node sonos/status/keuken/renderingcontrol/ 

Apparently this does not work. Can anyone get me on the right track?

**Comment by viimD** [comment]
Found it: https://www.npmjs.com/package/sonos2mqtt/v/1.4.0

**Comment by svrooij** [comment]
@viimD you can always take a look at the documentation page https://svrooij.github.io/sonos2mqtt
