### ISSUE TITLE
Question: How dows gorup volume controle work

### ISSUE THREAD

**Issue by svrooij** [svrooij/sonos2mqtt#136]
I'm also struggling with this issue. I figured out how to start for example Radio 3FM on my speakers. I do this by sending this message to the coördinator speaker 'wittekast keuken' (sonos/wittekast-keuken/control):
{    "command": "setavtransporturi",
    "input": "radio:s6707?sid=254&flags=32"}

This works fine, both the speaker 'wittekast keuken' and 'keuken' (which are in the same group), play 3FM. However, when I want to increase the volume of both speakers it does not work. I send the following message also to the coördinator speaker 'wittekast keuken' (sonos/wittekast-keuken/control):
{    "command": "volumeup",
    "input": 5}

Now only the volume of the 'wittekast keuken' is raised by 5. The volume of the member 'keuken' remains unchanged. Do I miss something somewhere?

_Originally posted by @viimD in https://github.com/svrooij/sonos2mqtt/issues/110#issuecomment-770197406_

**Comment by svrooij** [comment]
Volume is per speaker, but [some](https://svrooij.io/node-sonos-ts/sonos-device/methods.html#shortcuts) commands are automatically redirected to the group coordinator.

You can however send a special group command (to the coordinator of that group, else it will return an error).

Send an [advanced command](https://svrooij.io/sonos2mqtt/control/advanced.html) to the [GroupRenderingControlService](https://svrooij.io/node-sonos-ts/sonos-device/services/group-rendering-control-service.html).

Topic: `sonos/wittekast-keuken/control`
Payload:

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "GroupRenderingControlService.SetRelativeGroupVolume",
    "val": {
      "InstanceID": 0,
      "Adjustment": 20
    }
  }
}
```

This will execute the [SetRelativeGroupVolume](https://svrooij.io/node-sonos-ts/sonos-device/services/group-rendering-control-service.html#setrelativegroupvolume) command. The InstanceID always has to be `0` and the **Adjustment** can be any number between -100 and +100. This will be the relative adjustment. If the speakers where not at the same volume, the adjustment is also computed for all speakers separate.

**Comment by viimD** [comment]
Thanks Stephan! The use of advanced commands works like a charm!
