### ISSUE TITLE
Bug for stereo couple of two Sonos one?

### ISSUE THREAD

**Issue by heinz-otto** [svrooij/sonos2mqtt#137]
I have two different systems, there is working in both systems a stereo couple of Sonos one Boxes.
Both systems shows this stereo couple as two separate speakers with the same name, one could be controlled normally, the other don't get any updates of information.
I have a 5.1 system build with sonos Playbase, Subwoofer and two Sonos Play1 - this is working as one speaker shown as Sonos Playbase
Both system running the actual sonos2mqtt Version 3.1.1

Could I do anything to support you with informations for troubleshooting?

Kind regards
Otto

**Comment by svrooij** [comment]
This is related to https://github.com/svrooij/node-sonos-ts/issues/125 we are in the progress of surfacing the `Invisible` property of group members. Once it’s available we can use it to hide speakers in sonos2mqtt

**Comment by svrooij** [comment]
@heinz-otto the **Invisible** property is available in the latest [beta](https://github.com/svrooij/node-sonos-ts/releases/tag/v2.4.0-beta.4) of the sonos library. What should I do with it?

To my understanding the left player is hidden in the official sonos application. Should I just add the **Invisible** property to the [status object](https://svrooij.io/sonos2mqtt/topics.html#player-status). Or just don't output anything for this Invisible player?

**Comment by heinz-otto** [comment]
The Sonos Application shows one "Room" in the App for the Couple (L+R). Like my Room Wohnzimmer wich ist build from Playbase, Sub and 2x Play1. Only under Settings/Equalizer I have access to the different Boxes. 
For my Room "Wohnzimmer" the 4 Boxes will be shown in sonos2mqtt as one Player (as expected)
For my Room "Test" the 2 Boxes/Couple shown as two Boxes only the Left will getting the full updates. I could controlling both boxes a little bit different? Both Boxes have the same name in sonos2mqtt.
If I am putting this two boxes as surroundspeakers to my Sonos Beam - all is fine. Only one Player for this triple.
Is there a different handling for combination of Beam + Surround and only a Stereo Couple? Inside Sonos this feature isn't really new.

**Comment by svrooij** [comment]
I just have no experience with stereo pairs. So I'm wondering what the app should do. I think just hide the right player of the stereo pair might be the best solution.

**Comment by heinz-otto** [comment]
At this point, I am not shure, if the right or the left player will be the leader :-) I had done some investigation and may be, sonos2mqtt is doing the right job. A upnp Tool show the same situation, the stereo couple "Test" is shown like two players. The 4-tuple "Wohnzimmer" is shown as one.
![image](https://user-images.githubusercontent.com/25388112/107663121-4e02ea80-6c8b-11eb-867b-69c9fd1390be.png)
And there are no updates of transportstate to both players, see STOPPED state
![image](https://user-images.githubusercontent.com/25388112/107665822-219c9d80-6c8e-11eb-9c7e-16e6e3f16d53.png)
With the coordinatorUuid  RINCON_48A6B8195BE801400 from the other player, I could see the player is in a group and the Name is equal the other. 
A stereo couple is only like a group with the same name of players? May be that's ok ;-) I could respond of this.

**Comment by heinz-otto** [comment]
My Solution inside the Application (FHEM) is the following:
If **coordinatorUuid** and **uuid** ist NOT equal AND the **groupName** contains no + sign 
the Device should be a part of a stereocouple and not part of normal group.
