### ISSUE TITLE
Add additional commands

### ISSUE THREAD

**Issue by sebbo2002** [svrooij/sonos2mqtt#139]
Thank you for this great library. While testing the library, I noticed that some commands are still missing that I currently use in my home automation. As far as I can see, these are currently:

- [SetLEDState](https://svrooij.io/node-sonos-ts/sonos-device/services/device-properties-service.html#setledstate)
- [SetButtonLockState](https://svrooij.io/node-sonos-ts/sonos-device/services/device-properties-service.html#setbuttonlockstate)
- [SetNightmode](https://svrooij.io/node-sonos-ts/sonos-device/methods.html#shortcuts)
- [SetBass](https://svrooij.io/node-sonos-ts/sonos-device/services/rendering-control-service.html#setbass)
- [SetTreble](https://svrooij.io/node-sonos-ts/sonos-device/services/rendering-control-service.html#settreble)
- [AddMember](https://svrooij.io/node-sonos-ts/sonos-device/services/group-management-service.html#addmember)
- [RemoveMember](https://svrooij.io/node-sonos-ts/sonos-device/services/group-management-service.html#removemember)

Was there a reason for this or was it simply not needed until now? Otherwise, I would try to make a pull request for this at the weekend, if that's okay. Is there anything I should bear in mind?

**Comment by svrooij** [comment]
Hi @sebbo2002 those commands are not missing :wink:. They just don't have a shortcut (yet), you can call them by sending an [advanced command](https://svrooij.io/sonos2mqtt/control/advanced.html) which lets you call **all** the [sonos service commands](https://svrooij.io/node-sonos-ts/sonos-device/services/services.html)

If you want you can add them to the shortcut commands (to call them more quickly), in that case:

1. Add the lowercase command name [here](https://github.com/svrooij/sonos2mqtt/blob/beta/src/sonos-commands.ts)
2. Add the mapping to the sonos command [here](https://github.com/svrooij/sonos2mqtt/blob/beta/src/sonos-command-mapping.ts)
3. And please document them [here](https://github.com/svrooij/sonos2mqtt/blob/beta/docs/control/1-commands.md)

And it really helps a lot if you start from the beta branch and also send the PR to the beta branch. That way I can accept the pr without going to my computer and doing some merge magic.

The first command for instance can be controlled by sending the following to topic `sonos/uuid_of_speaker/control`:

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "DevicePropertiesService.SetLEDState",
    "val": {
      "DesiredLEDState": "On"
    }
  }
}
```

**Comment by sebbo2002** [comment]
I have made a PR (#140) for the shortcuts, I hope it's fine for you. I haven't had a chance to test the whole thing yet, I also somehow overlooked `joingroup` and `leavegroup` when I quickly looked through them. Thanks for that.

I'll close the issue for now, but if I run into any problems while testing, I'll get back to you. Thanks for your work and this great library 🎉
