### ISSUE TITLE
Neural voices

### ISSUE THREAD

**Issue by svrooij** [svrooij/sonos2mqtt#155]
Implement neural voices for TTS request

https://github.com/svrooij/node-sonos-ts/issues/146

**Comment by svrooij** [comment]
@christianeuropa with the latest release of sonos2mqtt you should be able to use the **engine** options for TTS, if you also updated your sonos-tts-polly instance that is.

This code can now be used
https://github.com/svrooij/node-sonos-ts/blob/8bf617855a4f5e36d4e6bcf45af96f4562236e4b/src/models/requests.ts#L99-L102

Related to https://github.com/svrooij/node-sonos-tts-polly/issues/10

**Comment by christianeuropa** [comment]
Where can I change the engine? With the payload:
{
  "command":"speak",
  "input": {
    "text": "Wir gehen heute einkaufen. Es wird bestimmt ein schöner Tag.",
    "endpoint": "https://your.tts.endpoint/api/generate",
    "lang": "de-DE",
    "gender": "female",
    "name": "Vicki",
    "engine": "neural",
    "volume": 30,    
    "onlyWhenPlaying": false,
    "delayMs": 700
  }
}

it doesn't work
