### ISSUE TITLE
Problem with docker image

### ISSUE THREAD

**Issue by peti69** [svrooij/sonos2mqtt#164]
I am using the latest image from docker hub and get

```
node:internal/modules/cjs/loader:936

  throw err;
  ^
Error: Cannot find module '/usr/src/app/lib/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v17.3.0
```
on the log.

**Comment by svrooij** [comment]
Environment?
Registry, ghcr or dockerhub?
Device architecture?

**Comment by peti69** [comment]
Image has been downloaded from dockerhub.

Device architecture is amd64.

Environment settings are:
NODE_VERSION = 16.9.1
YARN_VERSION = 1.22.5
SONOS2MQTT_RUNNING_IN_CONTAINER = true
SONOS2MQTT_DISTINCT = true
SONOS2MQTT_PREFIX = sonos2mqtt
SONOS2MQTT_DISCOVERY = false
SONOS2MQTT_FRIENDLYNAMES = uuid

**Comment by peti69** [comment]
WIth svrooij/sonos2mqtt:beta from dockerhub I still get:
```
node:internal/modules/cjs/loader:936

  throw err;
  ^
Error: Cannot find module '/usr/src/app/lib/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by svrooij** [comment]
Can you try the image on github registry.

https://github.com/svrooij/sonos2mqtt/pkgs/container/sonos2mqtt

I’m running this image on both amd64 and on a pi.
I have no clue where I should look for this problem.

**Comment by svrooij** [comment]
@peti69 can you confirm this issue is still around when using the image from the [github registry](https://github.com/svrooij/sonos2mqtt/pkgs/container/sonos2mqtt/?tag=beta), they should be the same but now I'm not sure.

`docker pull ghcr.io/svrooij/sonos2mqtt:3.2.0-beta.4`

You can re-open this issue if the issue is still around.
