### ISSUE TITLE
Sonos Favorites Question

### ISSUE THREAD

**Issue by j6s33m** [svrooij/sonos2mqtt#165]
I have several Sonos Favorites that I've made and like to play often, however, I cannot figure out for the life of me how to queue / play them with mqtt. I see all the code for how to queue Sonos playlists and specific music from the different platforms, but not playlists that sit in Sonos Favorites. Any help would be great.

**Comment by svrooij** [comment]
The [playback](https://svrooij.io/sonos2mqtt/control/playback.html) page describe how you can play an item. You'll need the track uri, depending on what is in you favorites, you'll either need call **settransporturi** for streams, or add it to the queue, for songs.

To figure out the required data, you'll need to [Browse your favorites](https://svrooij.io/sonos2mqtt/control/browse.html#favorites).

I must agree this can be documented better, and I'm open to suggestions.

**Comment by j6s33m** [comment]
Thanks for pointing me in the right direction. I'm doing a lot of testing in node-red and when I follow the directions in the "browse your favorites" section, I'm not getting the results in the debug window with my favorites. Am I doing something wrong? I've also checked the sonos2mqtt logs in portioner and am not getting anything in there either.

**Comment by svrooij** [comment]
If I send a mqtt message to `sonos/uuid/control` with the following payload, I'm getting something back:

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "GetFavorites",
    "reply": "GetFavoritesReply" 
  }
}
```

The `reply` parameter means, sent the output of this command to `sonos/uuid/{reply-value}`, `sonos/uuid/GetFavoritesReply` in this case. And I'm seeing that in the logs. Are you subscribing to the right topic?

I always use **MQTT Explorer** to tinker with mqtt.

![image](https://user-images.githubusercontent.com/1292510/151200280-d3e0464c-1838-4a68-a34c-760377073e51.png)

**Comment by j6s33m** [comment]
Yes...I found the mistake I was making as soon as I sent you that last message. Thank you! 

And MQTT Explorer is amazing...just downloaded it. Thanks for the recommendation

**Comment by j6s33m** [comment]
One more question, please. I can't figure out how to play this Apple Music radio station. Any recommendations?

      "TrackUri": "x-sonosapi-radio:radio:ra.985486583?sid=204&flags=8300&sn=10"

**Comment by svrooij** [comment]
At the moment this probably won't work, because it doesn't know what the metadata should be for those urls.

This application is "guessing" the metadata for a lot of urls.

Because you can load the metadata from. The favorite, you might be able to use the expert command. https://svrooij.io/sonos2mqtt/control/playback.html#play-a-single-item-for-experts

And set the metadata from the favorite item.

Maybe that data can also be generated from the url, but then you'll need to send both the url and the metadata. That is usually the data that is needed to guess the correct metadata, then we can add that to the metadata guesser and everybody can use Apple music radio.

**Comment by j6s33m** [comment]
I've been trying to used the expert command. I'm missing the "CdUdn".

Just downloaded Wireshark and have figured out how to sort on Port 1400, but literally have zero idea what I'm looking for. :)


`    {
      "AlbumArtUri": "https://is4-ssl.mzstatic.com/image/thumb/Features111/v4/cd/ea/5a/cdea5a14-9789-26f5-8714-17b1db8f1021/source/400x400cc.jpeg",
      "Title": "Music: Pure Country",
      "UpnpClass": "object.itemobject.item.sonos-favorite",
      "ItemId": "FV:2/61",
      "ParentId": "FV:2",
      "TrackUri": "x-sonosapi-radio:radio:ra.985486583?sid=204&flags=8300&sn=10",
      "ProtocolInfo": "x-sonosapi-radio:*:audio/x-sonosapi-radio:*"
    }`

**Comment by svrooij** [comment]
I would try the following `SA_RINCON2311_X_#Svc2311-0-Token`
That works for most services.

The UpnpClass, ItemId and ParentId can be copied from the metadata.

**Comment by svrooij** [comment]
We need extra information, you can re-open if you got extra info.
