### ISSUE TITLE
Configuration in Synology Docker Container

### ISSUE THREAD

**Issue by RossMax2** [svrooij/sonos2mqtt#176]
Hallo, 
I'am pretty much a beginner!

Installing and running the docker file on my Synology worked.
Obviously the Sonos speakers where found.
In MQTTFX I see some Sonos-Topics with plausible information.

but!

I have no Idea how to change the configuration.
How do I have to use the Synology-Terminal?
Where do I find the options.json?

Maybe someone can give me some hints.

**Comment by svrooij** [comment]
Just take the [docker-compose file](https://svrooij.io/sonos2mqtt/getting-started.html#docker-compose) and use [this](https://linuxhint.com/docker-compose-with-synology/) manual on how to use docker-compose on your nas.

docker compose is an easy way to run (and configure containers).

**Comment by RossMax2** [comment]
Thank you. I will try the tutorial.
