### ISSUE TITLE
Randomize AddToQueue

### ISSUE THREAD

**Issue by tiroso** [svrooij/sonos2mqtt#185]
I can successfully clear the queue and add a Spotify playlist.
But I can't adding them in a random order. Is this missing in the AddToQueue command? It is possible in the app, in the playlist. There are two buttons, one to add randomized and one to play normal.
If I add and switch the Playmode the first track is always the first one...and the Playmode is not normal ;)

**Comment by svrooij** [comment]
Have you seen the `playmode` [command](https://svrooij.io/sonos2mqtt/control/commands.html#supported-commands)?

those two buttons are combined in the playmode in the Sonos speaker. I would add the Sonos playlist, then change the desired playmode. I think the playmode is kept even if you clear the queue, but not sure.
