### ISSUE TITLE
Frage: Ist es möglich den amazon:effect zu nutzen?

### ISSUE THREAD

**Issue by Reinschki** [svrooij/sonos2mqtt#188]
Ich nutze Sonos2mqtt im Docker Container mit Fhem.

Frage:
Ist das nachfolgende nur falsch übergeben oder generell nicht möglich, da nicht implementiert?
`set MQTT2_RINCON_542A1BBE498001400 speak de-DE Hans 30 <speak>Kann mir bitte jemand in der Kueche zu Hilfe kommen?<amazon:effect name="whispered">Zur Belohnung gibt es moeglicherweise einen Nachschlag beim Nachtisch</amazon:effect></speak>`

Viele Grüße
Reiner

**Comment by svrooij** [comment]
I have no idea what this means. My main languages are Dutch and English, I only speak some highschool level german.
This looks like the FHEM integration, which I have no clue on how it works.

For the speech part, it probably uses my [polly-tts](https://github.com/svrooij/node-sonos-tts-polly) service, which currently has no support for effects. It is open-source however so if amazon supports that, this should also be possible by editing the polly tts service.

**Comment by Reinschki** [comment]
Hello, 
I understand that the Amazon effects are not supported at the moment. I will now translate my communication beforehand.

Thank you very much for your support!!!
