### ISSUE TITLE
favlist Readig empty after getting Sonos Favorites

### ISSUE THREAD

**Issue by HansMuff82** [svrooij/sonos2mqtt#198]
Hello!
I installed the Sonos system in Fhem as described in the Wiki. I got alle the favorites via "get Sonosbridge Favorites" in an json-like reading, but the favlist reading is still empty and I can't select an play a favorite in the Playerdevices. Am I missing something?

Fhem and Sonos2mqtt on docker, latest image

thx Markus

**Comment by svrooij** [comment]
I have no experience with Fhem, ask this question at the appropriate forum.
