### ISSUE TITLE
Sonos2Mqtt Unraid validate distrinct = true

### ISSUE THREAD

**Issue by aerom1017** [svrooij/sonos2mqtt#200]
Hello,
maybe a silly question, but how do I get sonos2mqtt_distrinct=true on unraid?

Thanks a lot

**Comment by svrooij** [comment]
Can you set environment variables there? `SONOS2MQTT_DISTINCT=true`

**Comment by aerom1017** [comment]
Hello svrooij, the problem is that I don’t find how to set environment variable on unraid 😢

**Comment by svrooij** [comment]
> Hello svrooij, the problem is that I don’t find how to set environment variable on unraid 😢

This is my 2 minute google result. Never used unraid so no garuntees.

https://forums.unraid.net/topic/108976-how-do-i-pass-an-emvironment-variable-to-a-docker/?do=findComment&comment=996109

**Comment by aerom1017** [comment]
Thank you so mutch Stephan, I will try it tomorrow.
