### ISSUE TITLE
sonos2mqtt stops after reboot

### ISSUE THREAD

**Issue by remko2000** [svrooij/sonos2mqtt#201]
I following the ' get started' (install in docker) en sonos2mqtt works fine. After a reboot sonosmqtt is not starting automatically. What's here the problem?

**Comment by svrooij** [comment]
I have no clue how to make regular docker containers run after a restart of the system.

That is why the [docker-compose](https://sonos2mqtt.svrooij.io/getting-started.html#run-sonos2mqtt-with-docker-compose) sample is higher. It has the `restart: unless-stopped` option right there in the sample.

**Comment by remko2000** [comment]
Okay dank

Mag ik nog 1 kleine vraag stellen. Ik worstel al een heel weekend met het juiste commando om bijv. skyradio via tunelin te activeren. Ik zie nergens een voorbeeld commando en volgens mij is dit ook een advanced commando. Heb jij toevallig een voorbeeld welke ik kan aanpassen naar mijn persoonlijk situatie?

Anders ben ik nog dagen bezig vermoed ik…..

Gr remko


Verstuurd vanaf mijn iPhone

Op 8 feb 2024 om 23:40 heeft Stephan van Rooij ***@***.***> het volgende geschreven:

﻿

I have no clue how to make regular docker containers run after a restart of the system.

That is why the docker-compose<https://sonos2mqtt.svrooij.io/getting-started.html#run-sonos2mqtt-with-docker-compose> sample is higher. It has the restart: unless-stopped option right there in the sample.
