### ISSUE TITLE
Group volume and balance

### ISSUE THREAD

**Issue by cheick66** [svrooij/sonos2mqtt#205]
Hi,
is it may be possible to add support for balance and group volume?

balance would be volume_RF and volume_LF, which is read only at the moment I gues.

Best regards
    Christian

**Comment by svrooij** [comment]
@cheick66 what do you mean by supporting group volume? You want to change the group volume?
You can use the [Advanced Command](https://sonos2mqtt.svrooij.io/control/advanced.html#advanced-commands) to execute the  [GroupRenderingControl -> SetGroupVolume](https://sonos-ts.svrooij.io/sonos-device/services/group-rendering-control-service.html#setgroupvolume) command.

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "GroupRenderingControlService.SetGroupVolume",
    "val": {
      "InstanceID": 0,
      "DesiredVolume": 20
    }
  }
}
```

Similarly you can also execute the [SetVolume](https://sonos-ts.svrooij.io/sonos-device/services/rendering-control-service.html#setvolume) command.
