### ISSUE TITLE
inflight 1.0.6 not supported. Memory leak.

### ISSUE THREAD

**Issue by aski71** [svrooij/sonos2mqtt#207]
Hi,

I installed sonos2mqtt and received the following warnings:

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

Can you please take care about this? 

Thanks.
Alex

**Comment by svrooij** [comment]
Which version did you install?

The latest `beta` has a lot of improvements and has vairly recently been updated with new packages.

**Comment by aski71** [comment]
Sorry. I was off for a while. My installed version is 3.2.0.
