### ISSUE TITLE
One topic for commands

### ISSUE THREAD

**Issue by flic** [svrooij/sonos2mqtt#21]
Hi.

I recently found this project when I was looking for alternatives to sonos-http-api. Love it, great job!

I'm currently in the process of migrating my Node-RED flows to it, and I was wondering of you would consider adding one command topic instead of or in addition to the multiple command topics approach you're using? Instead of publishing an empty message to sonos/set/Office/next or sonos/set/Office/play I would like to be able to sending next or play as a message to sonos/set/Office, for example. It would make thinks a lot simpler.

Even better would be a combined command and parameter JSON, 

`{
   "cmnd: "notify",
  "uri": "https://archive.org/download/Doorbell_1/doorbell.mp3",
  "volume": 10
}`

Thanks!

**Comment by svrooij** [comment]
Yeah why not, will have a go at it next week. Or you can send a PR, the code for parsing the commands send is quite easy to convert. I would prefer to have it both else it would break stuff
