### ISSUE TITLE
Right albumARTURI

### ISSUE THREAD

**Issue by jsponz** [svrooij/sonos2mqtt#23]
I am getting the following info:

1|bridge  | 2019-08-04 19:34:16.105 <info>  New track data for 7828CAE16694 {"id":null,"parentID":null,"title":"Ni La Hora","artist":"Juan Magan","album":"Ni La Hora","albumArtURI":"http://192.168.2.181:1400/getaa?s=1&u=x-sonosapi-hls-static%3acatalog%252ftracks%252fB07F4168P2%252f1c15af08-336a-4da1-9e50-d58636657b26%252facbea5c5-65ad-46a9-943f-090ab5924ef8%252fA3S8QLFWY3FC9K%252fn%252fUNLIMITED%252fba71af7f-eafe-4710-af94-30adc3db3c1c%252fUNLIMITED_STATION%252f3f258197-c78f-4a9b-8ba5-5210e76ffd6c%252f%3fsid%3d201%26flags%3d0%26sn%3d2","uri":"x-sonosapi-hls-static:catalog%2ftracks%2fB07F4168P2%2f1c15af08-336a-4da1-9e50-d58636657b26%2facbea5c5-65ad-46a9-943f-090ab5924ef8%2fA3S8QLFWY3FC9K%2fn%2fUNLIMITED%2fba71af7f-eafe-4710-af94-30adc3db3c1c%2fUNLIMITED_STATION%2f3f258197-c78f-4a9b-8ba5-5210e76ffd6c%2f?sid=201&flags=0&sn=2","duration":198,"queuePosition":2}

albumARTURI is not functional, because it returns an  URL of the speaker. Any help?

**Comment by svrooij** [comment]
Have you actually tried using it? It is totally useful because this address works when you’re in your local network.
This is the way how sonos provides this information. If you would click the link (while in your local network) it just shows the image.

**Comment by jsponz** [comment]
If I click on albumArtURI -> http://192.168.2.181:1400/getaa?s=1&u=x-sonosapi-hls-static%3acatalog%252ftracks%252fB07F4168P2%252f1c15af08-336a-4da1-9e50-d58636657b26%252facbea5c5-65ad-46a9-943f-090ab5924ef8%252fA3S8QLFWY3FC9K%252fn%252fUNLIMITED%252fba71af7f-eafe-4710-af94-30adc3db3c1c%252fUNLIMITED_STATION%252f3f258197-c78f-4a9b-8ba5-5210e76ffd6c%252f%3fsid%3d201%26flags%3d0%26sn%3d2

I get this: 

<img width="907" alt="Bildschirmfoto 2019-08-05 um 16 42 39" src="https://user-images.githubusercontent.com/12778286/62473002-31394d00-b7a0-11e9-8925-fb4da10b6497.png">

So, nothing is displayed. What am I doing wrong?

**Comment by svrooij** [comment]
You’re not on the right network. If you’re on the same network as your speakers. This would just work out of the box.

**Comment by jsponz** [comment]
I am in the same network 100 % sure...
