### ISSUE TITLE
issue with capital letters in command

### ISSUE THREAD

**Issue by Wuppi68** [svrooij/sonos2mqtt#24]
I send the following:

sonos/set/Dusche/play

and nothing happens except this in my syslog

Aug 14 17:31:31 kodi-1 sonos2mqtt[4251]: 2019-08-14 17:31:31.331 #033[37m#033[1m#033[41m<error>#033[49m#033[22m#033[39m Device with name dusche not found

sonos2mqtt 1.4.4 running on a raspbian

have you anything changed? --> yes :-) I found it in src/bridge :-)
downgraded to sonos2mqtt@1.4.3 and it is not working again

if you need further information feel free to order it :-)

**Comment by svrooij** [comment]
Can you explain what you mean?

This code https://github.com/svrooij/sonos2mqtt/blob/master/src/bridge.js#L102 should always make sure the devices are found no matter what.
In the next version I'll be putting all names to lowercase and replacing the spaces with dashes.

So a speaker with name **Dusche twei** will result in topics like `sonos/status/dusche-twei/track`

**Comment by Wuppi68** [comment]
Hi,

thanks for your asking ....

it was my fault :-(

disabled at my ubiquity wifi system broadcasts from LAN to Wifi .... and so sonos2mqtt discovered only LAN devices ....
while sonos-cli list-devices found everytime all of them

can you change the discovery?

Or easyly close this issue

Thanks

top tool !!!!!

**Comment by svrooij** [comment]
@Wuppi68 I'm checking out the possibilities for logical devices. I would like to run this bridge in docker. Than you cannot use discovery.

The steps would be, start with one IP and the get all the groups. But this needs to be build in the [sonos](https://github.com/bencevans/node-sonos) library. See [this issue](https://github.com/bencevans/node-sonos/issues/383)
