### ISSUE TITLE
Error executing joingroup

### ISSUE THREAD

**Issue by flic** [svrooij/sonos2mqtt#39]
I'm having some problems joining devices together into groups.

For example, I have one device named "Vardagsrum" and another named "Kök". I've tried the following:

/sonos/set/kök/command -> JSON {"cmd":"joingroup", "val":"Vardagsrum"}
/sonos/set/kök/joingroup -> String Vardagsrum

/sonos/set/kök/command -> JSON {"cmd":"joingroup", "val":"vardagsrum"}
/sonos/set/kök/joingroup -> String vardagsrum

...and the other way around. In all cases I get "<error> Error executing joingroup for Kök {}" in the logfile. Leavegroup, play, stop and so forth works just fine. I even tried renaming Kök to Kok to see if it was an UTF-8 problem, same result.

Am I doing something stupid? ;)

**Comment by svrooij** [comment]
What room is the coordinator? The coordinator is the group you started with when you joined the other groups.

What it does when you try join group is downloading all the groups and finding the coordinator that is in the group of the device you want to join.

[See here](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L236) I'll lookup a command for you to do some diagnostics tomorrow. With an alternative to join the other group without the join group command.

**Comment by flic** [comment]
I start with all players as standalone. Do I need to designate a specific player as coordinator before I try to join other players to it? I've just tried to join A to B with joingroup.

**Comment by svrooij** [comment]
If you pick player A, then press the group button next to it and add some other player. Player A will be the coordinator.

**Comment by flic** [comment]
Okay. And then, if I want to join player B to the new group I publish A to "/sonos/set/b/joingroup", right?

Still getting Error executing joingroup in the example above. I'll play around some more.

**Comment by svrooij** [comment]
There was a but in the sonos lib see https://github.com/svrooij/node-sonos-ts/pull/23

This will be fixed soon.
