### ISSUE TITLE
Title and artist are not set when streaming from TuneIn 

### ISSUE THREAD

**Issue by cheanrod** [svrooij/sonos2mqtt#43]
When streaming from TuneIn artist and title information are not parsed and only a stream URI is published under title.

```json
{"ts":1577457006391,
"name":"Bad",
"val":
{"title":"x-sonosapistream:...",
"albumArt":"http://192.168.178.XX:1400/...",
"trackUri":"x-sonosapi-stream:..."
}}
```
The information in the stream URI is cut for privacy reason.

**Comment by svrooij** [comment]
This is something in the sonos library, where I created an issue. This is open for PR's, or I will do it myself somewhere next week.
