### ISSUE TITLE
Multi architecture docker image

### ISSUE THREAD

**Issue by svrooij** [svrooij/sonos2mqtt#49]
Currently we are building a [linux/amd64](https://hub.docker.com/r/svrooij/sonos2mqtt) docker image, but the [base image](https://hub.docker.com/_/node/) supports multiple architectures.

This image should build without any problem for every platform supported by the base image, but I need some help setting up the automated builds. So in theory you can run this app on a raspberry pi in docker, but (for now) you should build it yourself on the raspberry pi until we have set-up automatic builds.

I should all go automatically, but I have no special preference for a specific platform.

- Github Actions
- Azure DevOps
- Docker hub builds

I found some template [here](https://github.com/rcarmo/azure-pipelines-multiarch-docker) but I'm kinda lost on how to implement it.

**Comment by svrooij** [comment]
I found a way that works with [buildx](https://github.com/docker/buildx). [result](https://hub.docker.com/layers/svrooij/sonos2mqtt/rasp/images/sha256-5f06a07d9ac9c7cb495594bbd626ca5c2743ff788363d4938383da75f3adea09)

It requires experimental features to be enabled.

```Shell
# First time only
docker buildx create --use
# Build and push
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t svrooij/sonos2mqtt:rasp --push .
```

Now a way to automate this in some CI/CD pipeline.

**Comment by cheanrod** [comment]
Hi, I saw you are working on the multi architecture docker image. Based on Azure, I suppose?

I created multi architecture images for one a my repositories successfully today by using Github actions. If you want I could prepare a PR for sonos2mqtt based on this action?

**Comment by svrooij** [comment]
@cheanrod THAT WOULD BE AWESOME!!!!

Currently I'm doing a manual multi-arch build with the above command, but yeah it's manual.... Would love to have it automated (in Github Actions)

**Comment by cheanrod** [comment]
No problem, I will prepare a PR. For the other repository it worked quite well after some trial and error.

For testing purpose I will push the images to my account on docker hub. You will have to change the docker tag (svrooij/sonos2mqtt) when accepting the PR.

**Comment by svrooij** [comment]
Maybe it's possible to use environment variables for the image name? That way you can set-it up in the Action settings? Not sure if github actions supports that?

Will you be changing anything to the dockerfile? My manual 3 architecture build is 3mb bigger (on the amd64 platform) then the automatically build version.

**Comment by cheanrod** [comment]
It already worked obviously. See here: https://hub.docker.com/r/cheanrod/sonos2mqtt/tags
I did not need to change anything in the dockerfile. I just works with buildx but I have no idea why the multi architecture build is bigger. 

And yes, there is an environment variable for GITHUB_REPOSITORY name. Luckily this name is the same on docker hub.
