### ISSUE TITLE
Group commands

### ISSUE THREAD

**Issue by flic** [svrooij/sonos2mqtt#51]
I just noticed that commands like for example sonos/cmd/pauseall doesn't work on a group. Same thing with sonos/room/pause for a grouped speaker. How do I send commands to a group?

**Comment by svrooij** [comment]
What is your zone configuration and what doesn’t work?
What is you OS? Do the events work (needed to manage group coordinator)? Docker or bare bones?

You can always use the [command](https://github.com/svrooij/sonos2mqtt#command) syntax to `Sonos/set/coordinator-name/adv-command` the command should be `AVTransportService.Pause`.
Can you test that?

Also does the music support pausing? Streams cannot be paused and should be stopped. I myself use the `toggle` command to my players and it just works.

I think this might have something to do with [this](https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L627-L629) statement. Will research next weekend.

**Comment by flic** [comment]
A big "never mind" on this one. Yesterday it didn't work, today everything works just as it should. Sorry 'bout that!
