### ISSUE TITLE
Grouped speakers get the status "playing"?

### ISSUE THREAD

**Issue by matthias-burgfried** [svrooij/sonos2mqtt#62]
Hello, I have observed a behavior that I do not understand. When I group a player (player 1) with a second player (player 2), the status of player 1 is "playing", although both players are not playing anything (they are stopped or paused).
Is this behavior intended?

**Comment by svrooij** [comment]
If your group a player with another, there is one “coordinator” that controls the playback, and the queue. The other player (the one listening to the coordinator) is actually playing the empty stream from the coordinator.

I’m not sure on how to solve this, maybe group playback status is a nice feature, what’s your opinion about that?

**Comment by matthias-schulz** [comment]
It would be fine, but I'm not sure if this is the most suitable solution. I installed node-sonos-http-api ([https://github.com/jishi/node-sonos-http-api](https://github.com/jishi/node-sonos-http-api)), where the grouped speaker shows the status of the coordinator. What do you think of this solution?

**Comment by svrooij** [comment]
Why not just "disable" the player in the ui if it's grouped? You can see the group events. In the official sonos app you can also not interact with the "child" players. You first have to ungroup them. What is the use case you're trying to solve?

**Comment by matthias-burgfried** [comment]
Sorry for my late answer. I have a somewhat complicated setting. In the living room I have a PLAY:5 and a One. Unfortunately, you can't assign these two speakers to one room, so I usually (not always) grouped them. If a radio station is played in the kitchen and the two loudspeakers in the living room should be added by a button (via node-red), then this doesn't work so easily/it often fails because I don't know if the two loudspeakers are already grouped or not.

**Comment by svrooij** [comment]
Closing this stale issue, if someone wants to fix this, please re-open and create a PR.
