### ISSUE TITLE
Initial run fails with message: Cannot read property 'ParseMember' of undefined

### ISSUE THREAD

**Issue by besynnerlig** [svrooij/sonos2mqtt#65]
**To reproduce:**
1) Delete any previous Docker container and image
2) Make an .env file as described
3) Issue command: `docker run --env-file .env -p 6329:6329 svrooij/sonos2mqtt`

```
Unable to find image 'svrooij/sonos2mqtt:latest' locally
latest: Pulling from svrooij/sonos2mqtt
c9b1b535fdd9: Pull complete
99c818a1969a: Pull complete
fced71a1b5bc: Pull complete
799240489e66: Pull complete
211283277c6a: Pull complete
aeb42f5bb289: Pull complete
9dd1d4ca5b76: Pull complete
0bb55f60af26: Pull complete
Digest: sha256:8439f6177616e05dc42af0d3d452bbf89ae0c1359e369ba16806e94545aa646f
Status: Downloaded newer image for svrooij/sonos2mqtt:latest
2020-02-18 20:14:36.965 <info>  sonos2mqtt 0.0.0-development starting
2020-02-18 20:14:36.966 <info>  Parsing url mqtt://MYHOST
2020-02-18 20:14:36.994 <info>  Start from device 192.168.4.82
2020-02-18 20:14:37.005 <info>  Connected to mqtt mqtt://MYHOST
2020-02-18 20:14:37.016 <error> Error in device discovery TypeError: Cannot read property 'ParseMember' of undefined
    at ParseGroup (/usr/src/app/node_modules/@svrooij/sonos/lib/services/zone-group-topology.service.js:71:95)
    at Array.map (<anonymous>)
    at ZoneGroupTopologyService.GetParsedZoneGroupState (/usr/src/app/node_modules/@svrooij/sonos/lib/services/zone-group-topology.service.js:59:23)
```
Here is my .env file:
```
# Set the IP of one known sonos speaker (device discovery doesnt always work inside docker.)
SONOS2MQTT_DEVICE=192.168.4.82
# Set the mqtt connection string
SONOS2MQTT_MQTT=mqtt://MYHOST
# Set the IP of the docker host (so node-sonos-ts knows where the events should be send to)
SONOS_LISTENER_HOST=192.168.4.44
# Set text-to-speech endpoint (optional)
SONOS_TTS_ENDPOINT=http://MYHOST:5601/api/generate
```
I had things up and running recently.

**Comment by svrooij** [comment]
I introduced a bug in [node-sonos-ts](https://github.com/svrooij/node-sonos-ts) that is fixed [here](https://github.com/svrooij/node-sonos-ts/pull/36). And will be released fixed when I merge in the new version.

New version up in an hour.

You're also using the the TTS server? Does it work for you? Do you like it?

**Comment by besynnerlig** [comment]
Thanks @svrooij 

I'll check it out as soon as it's available.

Yes, I'm using the TTS server and it's working great!

The whole concept of yours 

> heterogenous smart home environments where an MQTT message broker is used as the centralized message bus

is so brilliant. I MQTT-fy everything I can and it's the most stable and reliable part of my Home Automation system. I'm convinced its the best way to go.

I will definately make a donation for pizza and a beer when things are up and working. I will probably open a new ticket later for some other issues using the speak function that I've stumbeled upon.

Do you think it would be a good idea to start both sonos2mqtt and sonos-tts-polly in a single docker-compose file? I might have a look at that today... 

Please keep up the good work. I will mention your work in various forums whenever there is an opportunity. Thanks @svrooij 

// B Synnerlig

**Comment by svrooij** [comment]
> I'll check it out as soon as it's available.

It's available [build](https://github.com/svrooij/sonos2mqtt/runs/454794080?check_suite_focus=true) [dockerhub](https://hub.docker.com/r/svrooij/sonos2mqtt/tags)

> The whole concept of yours:
heterogenous smart home environments where an MQTT message broker is used as the centralized message bus

Not my idea 😉 , just following a great idea of someone else [mqtt-smarthome](https://github.com/mqtt-smarthome/mqtt-smarthome)

> is so brilliant. I MQTT-fy everything I can and it's the most stable and reliable part of my Home Automation system. I'm convinced its the best way to go.

Same here.

> Do you think it would be a good idea to start both sonos2mqtt and sonos-tts-polly in a single docker-compose file? I might have a look at that today...

Sure that is a good idea, I'm running all my home automation apps from a single docker-compose (somewhere in a private git repo, so I can just swap the device it's running on.)
