### ISSUE TITLE
UPnPError when executing speak while streaming TuneIn-station

### ISSUE THREAD

**Issue by besynnerlig** [svrooij/sonos2mqtt#70]
Running the latest version of  sonos2mqtt (v2.0.10) in Docker and whenever I publish a MQTT  message to **sonos/set/MYDEVICE/speak** , the message gets spoken but my Sonos speaker won't resume playing whatever Tune-in station they were playing.
Sonos2mqtt throws the following error message:
```
<error> Error executing speak for MYDEVICENAME {"Action":"SetAVTransportURI","FaultCode":"s:Client","Fault":"UPnPError","UpnpErrorCode":402,"name":"SonosError"}
```
I'm not sure if it's relevant but I have also tried running docker with the `--network host` flag. Unfortunately thats yielding the same error.

**The above error is only when streaming from a TuneIn-station.** 

However when playing an Album or when playing a Spotify playlist there are other issues:
Most times the spoken message fails and is replaced with a very short period of silence. (Timing issue?) (In my Sonos app I can see the message clip name showing up briefly) Sometimes the message gets spoken correctly. Playing is always resumed. Please advise me if you would you like me to submit a separate issue for that.

**Comment by svrooij** [comment]
This isn’t just an issue with the sonos2mqtt app. This is an issue in the [node-sonos-ts](https://github.com/svrooij/node-sonos-ts] library.

Anyway I’ll have a look at it tomorrow. Guessing it has something to do with the metadata.

According to the [specs](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf) page 86, the error code 402 means invalid arguments.

**Comment by svrooij** [comment]
You were right, the issue is fixed [here](https://github.com/svrooij/node-sonos-ts/tree/bug/metadata) will be released tomorrow.

Can you test it out tomorrow? If the second issue still exists in that new version, can you create a new issue?

**Comment by besynnerlig** [comment]
Thanks a lot. I will check it out tomorrow and let you know the results.

**Comment by besynnerlig** [comment]
Great work @svrooij 

I can confirm that the error message has now disappeared and that the TuneIn stream continues after a message has been spoken. 

Thank You!
