### ISSUE TITLE
Spoken message appears as a short gap of silence if streaming/playing

### ISSUE THREAD

**Issue by besynnerlig** [svrooij/sonos2mqtt#73]
On **v2.0.11**

When playing an Album or when playing a Spotify playlist on the Sonos, most times the spoken message fails and is replaced with a very short period of silence. (Timing issue?) (In my Sonos app I can see the message clip file name showing up briefly) Sometimes, randomly the message gets spoken correctly. When that happens resuming the streamin/playing wont happen. Furthermore volume level is not restored to the level that was actual when streaming/playing.

FWIW I don't know anything why this happens but it sounds like a series of commands are sent to Sonos asynchronously. Maybe Sonos can not handle that. Sonos might not have a command queue and as a result discards previous commands when a new comes in. Just a thought.

**Comment by svrooij** [comment]
The code for the notifications is here.
https://github.com/svrooij/node-sonos-ts/blob/de19aef35367bc8bda253ef89edd64c2bbf4beb2/src/sonos-device.ts#L268-L351

How short is the notification?
It might just not play it and then the restore everything back to normal will not work either because it error'ed out.

**Comment by besynnerlig** [comment]
Thanks.

The notification is a full sentence.

`MQTT Test Rule fired with payload: { "text": "Hejsan alla barn", "endpoint": "http://MYTTSSERVER:5601/api/generate","lang": "sv-SE", "gender": "female", "volume": 40, "onlyWhenPlaying": false }`

Where is options.timeout set?

I've execed into the container and I've found /usr/src/app/src/config.js but there is no timeout defined as faar as I can see. Maybe I can do some debugging if you help me a little bit about how to do it. I suspect that the timeout is set to low or that the asynchelper fails in some way ...

**Comment by besynnerlig** [comment]
If I add a wait statement after the TTS volume is set, things start to work. Maybe things are coming in to fast for Sonos.

In `/usr/local/lib/node_modules/sonos2mqtt/node_modules/@svrooij/sonos/lib/sonos-device.js` line 274:

```
        if (options.volume !== undefined) {
            await this.RenderingControlService.SetVolume({ InstanceID: 0, Channel: 'Master', DesiredVolume: options.volume });
            await new Promise(resolve => setTimeout(resolve, 500));
        }
```

Maybe it would be a good idea to add a small delay after every command that is succeeded by another one. What do you think?

Shall i make a PR for you?

**Comment by svrooij** [comment]
Who had ever thought that I could make it to fast.... 😁

Does that also mean that it just works if the volume isn't supplied with the PlayTTS command?

Yes please, the more contributors the better.

Can you create the async `sleep` method in the *AsyncHelper*. I would set the timeout to 200ms or even 150ms to keep the delay as short as possible.

Also the delay is probably only needed after the volume change, or maybe after commands that change stuff. Never had problem with the commands retrieving data. This is the only method that does several commands really short after each other.

**Comment by besynnerlig** [comment]
I'll do that tomorrow. Later, we could consider making the `async sleep` time configurable...

**Comment by besynnerlig** [comment]
> Does that also mean that it just works if the volume isn't supplied with the PlayTTS command? 

Actually, no it doesn't. After testing, I've found out that we do need a delay between _this.AVTransportService.SetAVTransportURI_ and _this.AVTransportService.Play_.

 
> Yes please, the more contributors the better. Ever done development on a TypeScript library?

No I haven't. I will just improvise, try it out here and trust that any mistakes will be spotted in the PR.

> Can you create the async `sleep` method in the _AsyncHelper_. I would set the timeout to 200ms or even 150ms to keep the delay as short as possible.

That won't help because the _AsyncHelper_ isn't used when setting the Volume. Maybe it should be used. However that's above my experience level. 

> Also the delay is probably only needed after the volume change, or maybe after commands that change stuff. Never had problem with the commands retrieving data. This is the only method that does several commands really short after each other.

Yeah, I agree.

I make that PR now so that we can discuss the specific code by reviewing the suggested code. It's easier than doing it here. Please feel free to suggest any type of changes in the PR.

Cheers!

**Comment by svrooij** [comment]
1. create a fork of [node-sonos-ts](https://github.com/svrooij/node-sonos-ts).
 2. run `npm install` in the repository
 3. Change the code you want
 4. Press F5 (in VS Code), while the [play-notification sample](https://github.com/svrooij/node-sonos-ts/blob/master/examples/play-notification.js) is open.

That should build (actually transpile) the typescript to javascript, and run the current open sample. The code in the repository is only TypeScript and the **lib**-folder is automatically ignored. 

> That won't help because the AsyncHelper isn't used when setting the Volume. Maybe it should be used. However that's above my experience level.

I mean that it might be better to put the delay function in the [AsyncHelper](https://github.com/svrooij/node-sonos-ts/blob/master/src/helpers/async-helper.ts) class. That code might be needed in other places in the library. Something like

```typescript
static async Delay(milliseconds: number): Promise {
  return await new Promise(resolve => setTimeout(resolve, 500));
}
```

Then you can use it by calling:
```typescript
await AsyncHelper.Delay(150);
```

Closing this issue, moving to https://github.com/svrooij/node-sonos-ts/issues/38

**Comment by svrooij** [comment]
Version 2.0.12 has a fix for this. It allows for setting a delayMs in TTS or notification that should solve the issue.

Also the reverting doesn’t try to revert the track for streaming items. That should also make up for some of the errors.
