### ISSUE TITLE
Is it possible to play notifications using a local file?

### ISSUE THREAD

**Issue by besynnerlig** [svrooij/sonos2mqtt#74]
I'd like to play a notification stored in a mp3 file on local file system. 

So I've tried posting to MQTT Topic: `sonos/set/MYROOMNAME/notify` with payload: `{ "trackUri": "file://opt/openhab/conf/sounds/katching.mp3", "volume": 40, "timeout": 15, "onlyWhenPlaying": false }` and some other variants but without success.

Is it possible to do what I want? If not, can it be put on the list of requests for enhancements?

**Comment by svrooij** [comment]
Sonos has a way to play mp3 files from a file share (like a nas). You would be able to play it when it’s hosted on a file share or a http server.
(If you’re using the the TTS server, (which runs a webserver), you could put it in the cache folder.)

**Comment by besynnerlig** [comment]
Thanks! That's a great idea. It works very well.
