### ISSUE TITLE
Problem with the setting --distinct

### ISSUE THREAD

**Issue by Mib68** [svrooij/sonos2mqtt#88]
Hello, 

I like this git for my sonos player, but I've a problem I didnt undestand hox to make the setting on true.
I would like to use Distinct messages but I Don't find how to use it. 

I use docker to use sonos2mqtt and I've created the file .env but I dont find how to change the settings --distinct Simply 

Thanks for your help, to help me to understand this

**Comment by svrooij** [comment]
First i'm curious on why you would want to use the distinct options 😉 

I think you can set it by adding `SONOS2MQTT_DISTINCT=TRUE` to the `.env` file.

**Comment by svrooij** [comment]
Documentation fixed in #89

**Comment by matthias-burgfried** [comment]
Unfortunately, it does not work.
