### ISSUE TITLE
"prefix" not working for control

### ISSUE THREAD

**Issue by dgmltn** [svrooij/sonos2mqtt#91]
When I use the prefix argument (through docker as `-e SONOS2MQTT_PREFIX=devices/sonos`) topics get populated correctly but my `control` commands seem to be ignored.

**Comment by svrooij** [comment]
It does work when you change the prefix, but it doesn't like the `/` in the prefix because of how it is parsed.

https://github.com/svrooij/sonos2mqtt/blob/master/src/smarthome-mqtt.ts#L89-L93

**Comment by dgmltn** [comment]
Thanks so much! Fastest bugfix ever.

**Comment by svrooij** [comment]
https://github.com/sponsors/svrooij 😜
