### ISSUE TITLE
SetAVTransportURI command not working for live streams?

### ISSUE THREAD

**Issue by dgmltn** [svrooij/sonos2mqtt#92]
Like the title says, I can't get SetAVTransportURI to work for live radio streams. I know this uri should work because it's what I use in my own android app (using a library I've developed). I've tried both of these and they're met with different error messages.

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "SetAVTransportURI",
    "val": {
      "InstanceID": 0,
      "CurrentURI": "x-rincon-mp3radio://http://ice3.somafm.com/groovesalad-64-aac",
      "CurrentURIMetaData": ""
    }
  }
}
```
=>
```log
2020-05-25T01:38:53.445Z [Debug] Mqtt parsing adv-command for rincon_b8e93783163601400
2020-05-25T01:38:53.447Z [Warning] Error executing adv-command for Office (RINCON_B8E93783163601400)
 TypeError: trackUri.replace is not a function
    at Function.GuessTrack (/usr/src/app/node_modules/@svrooij/sonos/lib/helpers/metadata-helper.js:104:50)
    at Function.GuessMetaDataAndTrackUri (/usr/src/app/node_modules/@svrooij/sonos/lib/helpers/metadata-helper.js:95:41)
    at SonosDevice.SetAVTransportURI (/usr/src/app/node_modules/@svrooij/sonos/lib/sonos-device.js:374:59)
    at SonosDevice.ExecuteCommand (/usr/src/app/node_modules/@svrooij/sonos/lib/sonos-device.js:138:48)
    at Function.ExecuteCommand (/usr/src/app/lib/sonos-command-mapping.js:17:41)
    at Function.ExecuteControl (/usr/src/app/lib/sonos-command-mapping.js:7:46)
    at EventEmitter.<anonymous> (/usr/src/app/lib/sonos-to-mqtt.js:79:67)
    at EventEmitter.emit (events.js:310:20)
    at SmarthomeMqtt.handleIncomingMessage (/usr/src/app/lib/smarthome-mqtt.js:97:29)
    at MqttClient.<anonymous> (/usr/src/app/lib/smarthome-mqtt.js:35:74)
```

```json
{
	"command": "setavtransporturi",
	"input": "x-rincon-mp3radio://http://ice3.somafm.com/groovesalad-64-aac"
}
```
=> 
Causes an error in the sonos app, a toast that says 
```
Unable to play 'groovesalad-64-aac' - cannot connect to http%3a because the server cannot be found
```

**Comment by svrooij** [comment]
The first command tries to execute the **SetAVTransportURI** command on the sonos device class, which only accepts 1 parameter https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L410-L413

This isn't the same as the **AVTransportService.SetAVTransportURI** which accepts your specified parameters 

You could call it by using:
```JSON
{
  "command": "adv-command",
  "input": {
    "cmd": "SetAVTransportURI",
    "val": "x-rincon-mp3radio://http://ice3.somafm.com/groovesalad-64-aac"
  }
}
```

That results in the same code as with you other command https://github.com/svrooij/sonos2mqtt/blob/master/src/sonos-command-mapping.ts#L70-L71 .

Problem is that the library does some uri encoding, apparently it doesn't do a good job for this url. (the `http://...` is encoded as `http%3a//...`), and I just found this is even in the code (the not doing a great job part) https://github.com/svrooij/node-sonos-ts/blob/master/src/helpers/xml-helper.ts#L81-L87

## Solution (/workaround)

If you just remove the `http://` part from the url the commands start working (if you send the correct payload).

Can you confirm this helps?

**Comment by dgmltn** [comment]
Yes, this does help! This command appears to work:
```json
{
	"command": "setavtransporturi",
	"input": "x-rincon-mp3radio://ice3.somafm.com/groovesalad-64-aac"
}
```
Although it seems to choke on the colon again here:
```json
{
	"command": "setavtransporturi",
	"input": "x-rincon-mp3radio://ice3.somafm.com:80/groovesalad-64-aac"
}
```

Your input to the `adv-command` works too (after removing the `://` in my stream url). I use the CurrentURIMetaData parameter to set the title of the station. I stuff this ugly chunk of xml into the CurrentURIMetaData parameter in the SetAVTransportURI command:

```
        <DIDL-Lite xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:r="urn:schemas-rinconnetworks-com:metadata-1-0/" xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
          <item id="R:0/0/49" parentID="R:0/0" restricted="true">
            <dc:title>$title</dc:title>
            <upnp:class>object.item.audioItem.audioBroadcast</upnp:class>
            <desc id="cdudn" nameSpace="urn:schemas-rinconnetworks-com:metadata-1-0/">SA_RINCON65031_</desc>
          </item>
        </DIDL-Lite>
```

**Comment by svrooij** [comment]
How about (the node-sonos-ts library also has some metadata generation build-in):

```json
{
  "command": "adv-command",
  "input": {
    "cmd": "AVTransportService.SetAVTransportURI",
    "val": {
      "InstanceID": 0,
      "CurrentURI": "x-rincon-mp3radio://ice3.somafm.com/groovesalad-64-aac",
      "CurrentURIMetaData": {
        "Title": "your_title",
        "UpnpClass": "object.item.audioItem.audioBroadcast",
        "ItemId": "R:0/0/49",
        "CdUdn": "SA_RINCON65031_"
    }
  }
}
```

**Comment by dgmltn** [comment]
Yes! That worked, and it's so much less ugly too 👍
