### ISSUE TITLE
The name of the group doesn't change.

### ISSUE THREAD

**Issue by matthias-burgfried** [svrooij/sonos2mqtt#94]
I use the current docker build and have observed that the group name does not change when I group speakers.

Grouped:
`sonos/RINCON_B8E9111111111111 {"uuid":"RINCON_B8E9111111111111","name":"Bath","groupName":"Bath","coordinatorUuid":"RINCON_B8E9111111111111","transportState":"PLAYING","playmode":"NORMAL","ts":1590419121686,"volume":{"Master":43,"LF":100,"RF":100},"mute":{"Master":false,"LF":false,"RF":false}}`

Not grouped:
`sonos/RINCON_B8E9111111111111 {"uuid":"RINCON_B8E9111111111111","name":"Bath","groupName":"Bath","coordinatorUuid":"RINCON_B8E9111111111111","currentTrack":{"AlbumArtUri":"http://192.168.1.23:1400/getaa?s=1&u=x-sonosapi-stream:s25111%3fsid%3d254%26flags%3d8224%26sn%3d0","Title":"radioeins vom rbb","UpnpClass":"object.item","ItemId":"-1","ParentId":"-1","TrackUri":"x-sonosapi-stream:s25111?sid=254&flags=8224&sn=0","ProtocolInfo":"sonos.com-http:*:application/octet-stream:*"},"enqueuedMetadata":{"Title":"radioeins vom rbb","UpnpClass":"object.item.audioItem.audioBroadcast","ItemId":"-1","ParentId":"-1"},"transportState":"STOPPED","playmode":"NORMAL","ts":1590419234677,"volume":{"Master":43,"LF":100,"RF":100},"mute":{"Master":false,"LF":false,"RF":false}}`

**Comment by matthias-burgfried** [comment]
I have stopped and deleted the container and changed something in the env file and now it works. Maybe I had a typo in my env file. :/

**Comment by matthias-burgfried** [comment]
This is where it gets weird. The group name remains the same as it was when sonos2mqtt was started.

**Comment by svrooij** [comment]
I'll try to figure it out later today.
Never had problems with this myself though. (But I must say I haven't checked the group name in a while. I'm only using the coordinator attribute to start some automation

**Comment by dgmltn** [comment]
I was about to ask about this same issue. When I `sonos/set/bathroom/joingroup` as well as when I `sonos/set/bathroom/leavegroup` the group name doesn't change, nor does `coordinatorUuid`. I checked back hours later and the group name and coordinator had changed but they were out of date again.

**Comment by svrooij** [comment]
To be clear you are talking about the event with all the data of the speaker, and not the distinct events right?

**Comment by matthias-burgfried** [comment]
It affects both messages. The group attribute of `sonos/RINCON_XXX` doesn't change and `sonos/status/name_of_speaker/group` doesn't trigger.

**Comment by svrooij** [comment]
There was an error in the main library. It will be resolved soon https://github.com/svrooij/node-sonos-ts/pull/57

**Comment by svrooij** [comment]
Will be released any minute now.

**Comment by svrooij** [comment]
The docker image is building https://github.com/svrooij/sonos2mqtt/actions/runs/115628531

**Comment by svrooij** [comment]
![image](https://user-images.githubusercontent.com/1292510/82893101-ce908800-9f50-11ea-9dad-563483a5709e.png)
And [mqtt explorer](https://github.com/thomasnordquist/MQTT-Explorer) shows the group changes.

@all-contributors please add @matthias-burgfried for bugs
@all-contributors please add @dgmltn for bugs
